---
- name: Scale down replicas in Kubernetes cluster
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: pingpong-ns

  tasks:
    - name: Scale down pingpong-deployment
      kubernetes.core.k8s_scale:
        kubeconfig: "{{ kubeconfig_file }}"      
        name: pingpong-deployment
        namespace: "{{ namespace_name }}" # Replace with your desired namespace
        kind: Deployment
        replicas: 2  # Replace with the desired number of replicas
        state: present
