- hosts: localhost
  gather_facts: false
  tasks:
  
  # Add replicas at 8:00
    - name: Scale replicas up
      command: kubectl scale deployment pingpong-deployment --replicas=6
      when: "'{{ lookup('pipe','date +%H:%M') }}' == '08:00'"
      
  # Delete replicas at 13:00
    - name: Scale replicas down
      command: kubectl scale deployment pingpong-deployment --replicas=4
      when: "'{{ lookup('pipe','date +%H:%M') }}' == '13:00'"

