---
- name: Scale down Kubernetes deployment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Scale down deployment
      kubeconfig: '~/.kube/config'
      command: kubectl scale deployment pingpong-deployment --replicas=2
