---
- name: Scale down Kubernetes deployment
  hosts: localhost
  gather_facts: false

  vars:
    deployment_name: pingpong-deployment
    replicas: 2

  tasks:
    - name: Scale down deployment
      command: kubectl scale --replicas={{ replicas }} deployment/{{ deployment_name }}
